version: '3.4'
services:
  swoft:
    image: swoft/swoft
#    for local develop
    command: php -S 127.0.0.1:13300
    container_name: swoft-srv-myread
    environment:
      - APP_ENV=dev
      - TIMEZONE=Asia/Shanghai
    restart: always
#    depends_on:
#      - mysql
#      - redis
    ports:
      - "28306:18306"
      - "28307:18307"
      - "28308:18308"
    volumes:
      - ./:/var/www/swoft
      # - ./runtime/ng-conf:/etc/nginx
      # - ./runtime/logs:/var/log

#  mysql:
#    image: mysql
#    container_name: mysql-srv-myread
#    environment:
#      - MYSQL_ROOT_PASSWORD=123456
#    ports:
#      - "23306:3306"
#    volumes:
#      - ./runtime/data/mysql:/var/lib/mysql
#    restart: always
#
#  redis:
#    container_name: redis-srv-myread
#    image: redis:4-alpine
#    ports:
#      - "26379:6379"
#    sysctls:
#      net.core.somaxconn: 65535
#    restart: always
